"""create livestock_events table

Revision ID: 44f90c1921e6
Revises: 7b54d85c0913
Create Date: 2026-02-15 23:34:33.052951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f90c1921e6'
down_revision: Union[str, Sequence[str], None] = '7b54d85c0913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'livestock_events',
        sa.Column('id', sa.String(), nullable=False),

        sa.Column('camera_id', sa.String(), nullable=False),
        sa.Column('livestock_type', sa.String(), nullable=False),
        sa.Column('direction', sa.String(), nullable=False),

        sa.Column('track_id', sa.Integer(), nullable=True),

        sa.Column('image_path', sa.String(), nullable=True),
        sa.Column('vehicle_image_path', sa.String(), nullable=True),

        sa.Column('confidence', sa.Float(), nullable=True),

        sa.Column('event_time', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),

        sa.ForeignKeyConstraint(
            ['camera_id'],
            ['cameras.id'],
            ondelete="CASCADE"
        ),

        sa.PrimaryKeyConstraint('id')
    )

    # Индексы (очень важно)
    op.create_index('ix_livestock_camera', 'livestock_events', ['camera_id'])
    op.create_index('ix_livestock_event_time', 'livestock_events', ['event_time'])
    op.create_index('ix_livestock_type', 'livestock_events', ['livestock_type'])
    op.create_index('ix_livestock_direction', 'livestock_events', ['direction'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livestock_events')
    # ### end Alembic commands ###
